name: "jPipe Runner"
description: "GitHub Action to run justification diagrams of jpipe"
author: "Jason Lyu"

inputs:
  jd_file:
    description: "Path to the justification .jd file"
    required: true
  variable:
    description: "Define one or more variables in the format NAME:VALUE, separated by newlines"
    required: false
  library:
    description: "Specify one or more Python libraries to load, separated by newlines"
    required: false
  diagram:
    description: "Specify diagram pattern or wildcard"
    required: false
    default: "*"
  dry_run:
    description: "Perform a dry run without actually executing justifications"
    required: false
    default: "false"
  version:
    description: "jPipe Runner version to use, e.g. '0.0.1'. The main branch version is used by default"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install jpipe-runner
      shell: bash
      run: |
        pip install -U 'git+https://github.com/ace-design/jpipe-runner.git@${{ inputs.version }}'

    - name: Run jpipe-runner
      shell: bash
      run: |
        CMD="python -m jpipe_runner '${{ inputs.jd_file }}'"
        if [[ "${{ inputs.variable }}" != "" ]]; then
          while IFS= read -r line; do
            if [[ -n "$line" ]]; then
              CMD+=" --variable '${line}'"
            fi
          done <<< "${{ inputs.variable }}"
        fi
        if [[ "${{ inputs.library }}" != "" ]]; then
          while IFS= read -r line; do
            if [[ -n "$line" ]]; then
              CMD+=" --library '${line}'"
            fi
          done <<< "${{ inputs.library }}"
        fi
        if [[ "${{ inputs.diagram }}" != "" ]]; then
          CMD+=" --diagram '${{ inputs.diagram }}'"
        fi
        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
          CMD+=" --dry-run"
        fi
        echo "Running command: $CMD"
        eval $CMD
