flowchart LR

    subgraph Input
    direction TB
    A1("JD Files (*.jd)")
    A2("Python Scripts (*.py)")
    end

    subgraph "jPipe Runner"
    direction TB

    subgraph Core
    A1 --> P[Parser]
    A2 --> R[Runtime]
    P --> M([JD Models])
    M --> E[Engine]
    R --> E
    end

    E --> O[Runner]
    end

    O --> B(CLI / Pipeline Output)

    style Input stroke-dasharray:5 5
    style subGraph2 stroke-dasharray:5 5
